### PR TITLE
Allow compatibility with Cython 3.x

### PR DESCRIPTION
**Pull request by Marion-Artigaut**
This request is an attempt to fix Issue #9 as described in https://stackoverflow.com/questions/64932145/cython-compile-error-cannot-assign-type-double-to-int-using-mingw64-in-win.

### CODE REVIEW

**Comment by Marion-Artigaut** [comment]
The current fix works with Cython 3.0.0 in GitHub actions with the following code: 

```
name: CI testing 

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.x']

    name: Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install numpy matplotlib scipy python-igraph
          python -m pip install --upgrade pytest 
          python -m pip install triangle
          python -m pip install cython==3.0.0

      - name: Clone PyTetgen 
        run: |
          git clone https://github.com/Marcello-Sega/pytetgen.git
          
      - name: Modify PyTetgen
        run: |
          cd pytetgen
          sed --in-place '1s/^/#!python\n# cython: language_level=2\n/' pytetgen/pytetgen.pyx
          
      - name: Build PyTetgen
        run: |
          cd pytetgen
          python setup.py build_ext --inplace

      - name: Set pythonpath with pwd and pytetgen
        run: |
          echo "PYTHONPATH=$(pwd):$(pwd)/pytetgen" >> $GITHUB_ENV

      - name: Run tests 
        run: pytest 
```

**Comment by Marcello-Sega** [comment]
Dear Marion, thanks for opening the issue and for the pull request. I just wondered if it weren't better to simply go for integer division with `//` and keep python3 semantics in cython? What's your opinion?

**Comment by szhorvat** [comment]
>     - name: Install dependencies
>             run: |
>               python -m pip install numpy matplotlib scipy python-igraph



Please do not use `pip install python-igraph`. Simply use `pip install igraph`. See https://github.com/igraph/python-igraph/issues/699

**Comment by Marion-Artigaut** [comment]
Dear Marcello, 
I have not checked the remainder of the code to see if any other errors were raised with python3 semantics. It would I agree be better to do a full update. I am not as familiar with all the ins and outs of the code like you. Would you expect more work for migration to v3.x of cython? 
See documentation: https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html

**Comment by Marcello-Sega** [comment]
@Marion-Artigaut could you have a look if #11 fixes it for you as well ?

**Comment by Marcello-Sega** [comment]
Fixed by #11

**Pull request closed without merging**
